# Sudo required for doing docker build
sudo: required
services:
- docker

# Download whatever version of DSE we're creating an image for
install:
- ./build/download.sh

# Build the docker image
script:
- ./build/docker-build.sh

# If successful, see if we need to publish also
after_success:
- ./build/travis-publish.sh
